In [2]:
!pip install torch -q

In [3]:
import torch
import torch.nn as nn

In [11]:
torch.arange(5).expand((1, -1))

tensor([[0, 1, 2, 3, 4]])

In [31]:
input = torch.randn((4, 3, 224, 224))

In [32]:
import torch.nn as nn
conv = nn.Conv2d(
                 in_channels = 3, 
                 out_channels = 768, 
                 kernel_size = 16, 
                 stride = 16, 
                 padding='valid')

In [33]:
out = conv(input)

In [36]:
out.flatten(2).shape

torch.Size([4, 768, 196])

In [35]:
out.shape

torch.Size([4, 768, 14, 14])

In [37]:
embed = nn.Embedding(1024, 768)

In [39]:
embed(torch.arange(4)).shape

torch.Size([4, 768])

In [10]:

import torch
a = torch.zeros(4, 5)

In [12]:
a.unsqueeze(-1).expand(-1, -1, 10).shape


torch.Size([4, 5, 10])

In [1]:
import torch
a = torch.tensor([1], dtype=torch.float16)

In [11]:
a = torch.ones(2, 2, 4, 4)

In [19]:
a.cumsum(-1)[:, -1].shape

torch.Size([2, 4, 4])

In [20]:
b = torch.ones(2, 5)

In [28]:
c = torch.tensor([[1, 1, 0, 1, 1]]).expand(2, -1)
c.shape

torch.Size([2, 5])

In [30]:
(b.cumsum(-1)).masked_fill_((c == 0), 1)

tensor([[1., 2., 1., 4., 5.],
        [1., 2., 1., 4., 5.]])

In [46]:
a = torch.ones(1, 10)

In [51]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])